import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logoImg from "@/public/logo.svg";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useUserProfile } from "./components/ContextProvider";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const { email, image_source } = useUserProfile();
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
  const memoizedEmailText = useMemo(
    () => (windowWidth > 768 ? email : ""),
    [email, windowWidth]
  );

  const isHeaderSticky = () => router.pathname !== "/folder";

  useEffect(() => {
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header>
          <div>
            <Link href="/">
              <Image src={logoImg} alt="logoImg" />
            </Link>
            {/* {image_source ? (
          <UserProfileContainer>
            <UserProfileImg src={image_source} alt="userProfileImg" />
            <span>{memoizedEmailText}</span>
          </UserProfileContainer>
        ) : (
          <StyledLoginLink to="/signin">로그인</StyledLoginLink>
        )} */}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
