export { default as IconFacebook } from './IconFacebook';
export { default as IconInstagram } from './IconInstagram';
export { default as IconKebabMenu } from './IconKebabMenu';
export { default as IconLink } from './IconLink';
export { default as IconLogo } from './IconLogo';
export { default as IconSearch } from './IconSearch';
export { default as IconStar } from './IconStar';
export { default as IconTwitter } from './IconTwitter';
export { default as IconYoutube } from './IconYoutube';
