import App from "@/pages/_app";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>weekly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <App />
      </body>
    </>
  );
}
